"""Initial

Revision ID: a45cd7caca60
Revises:
Create Date: 2025-10-13 19:50:30.392110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a45cd7caca60"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_summaries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("project_name", sa.String(length=255), nullable=False),
        sa.Column("total_seconds", sa.Float(), nullable=False),
        sa.Column("digital_time", sa.String(length=20), nullable=True),
        sa.Column("text_time", sa.String(length=50), nullable=True),
        sa.Column("percent", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_date", "project_summaries", ["date"], unique=False)
    op.create_index("idx_date_project", "project_summaries", ["date", "project_name"], unique=True)
    op.create_index("idx_project", "project_summaries", ["project_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_project", table_name="project_summaries")
    op.drop_index("idx_date_project", table_name="project_summaries")
    op.drop_index("idx_date", table_name="project_summaries")
    op.drop_table("project_summaries")
    # ### end Alembic commands ###
